"""add_ai_api_keys_to_user_settings

Revision ID: 16f1698c735e
Revises: 1c8cf8cb8eeb
Create Date: 2026-06-03 11:22:47.730910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '16f1698c735e'
down_revision: Union[str, None] = '1c8cf8cb8eeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('claude_api_key_enc', sa.TEXT(), nullable=True))
    op.add_column('user_settings', sa.Column('deepseek_api_key_enc', sa.TEXT(), nullable=True))
    op.add_column('user_settings', sa.Column('gemini_api_key_enc', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'gemini_api_key_enc')
    op.drop_column('user_settings', 'deepseek_api_key_enc')
    op.drop_column('user_settings', 'claude_api_key_enc')
    # ### end Alembic commands ###
