"""add_cards_table_and_settings

Revision ID: 1c8cf8cb8eeb
Revises: b4ebc3a4ddab
Create Date: 2026-04-24 07:38:57.338068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1c8cf8cb8eeb'
down_revision: Union[str, None] = '792d6ae341f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cards',
    sa.Column('uuid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_uuid_bidx', sa.TEXT(), nullable=False),
    sa.Column('title_enc', sa.TEXT(), nullable=False),
    sa.Column('text_enc', sa.TEXT(), nullable=False),
    sa.Column('theme_enc', sa.TEXT(), nullable=False),
    sa.Column('scope_enc', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_cards_user_uuid_bidx'), 'cards', ['user_uuid_bidx'], unique=False)
    op.add_column('user_settings', sa.Column('ai_feature_enabled', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'ai_feature_enabled')
    op.drop_index(op.f('ix_cards_user_uuid_bidx'), table_name='cards')
    op.drop_table('cards')
    # ### end Alembic commands ###
