"""add username and email change track

Revision ID: 792d6ae341f8
Revises: r9s0t1u2v3w4
Create Date: 2026-04-17 20:44:08.243227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '792d6ae341f8'
down_revision: Union[str, None] = 'r9s0t1u2v3w4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_username_change', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('last_email_change', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_email_change')
    op.drop_column('users', 'last_username_change')
    # ### end Alembic commands ###
