"""add_ai_integration_and_cards

Revision ID: 7c9db47683df
Revises: 792d6ae341f8
Create Date: 2026-06-10 17:36:16.116021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7c9db47683df'
down_revision: Union[str, None] = '792d6ae341f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cards',
    sa.Column('uuid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_uuid_bidx', sa.TEXT(), nullable=False),
    sa.Column('title_enc', sa.TEXT(), nullable=False),
    sa.Column('text_enc', sa.TEXT(), nullable=False),
    sa.Column('theme_enc', sa.TEXT(), nullable=False),
    sa.Column('scope_enc', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_cards_user_uuid_bidx'), 'cards', ['user_uuid_bidx'], unique=False)
    op.create_table('user_ai_providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_uuid_bidx', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('api_key_enc', sa.TEXT(), nullable=True),
    sa.Column('selected_model', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_uuid_bidx', 'provider', name='uq_user_ai_provider')
    )
    op.create_index(op.f('ix_user_ai_providers_user_uuid_bidx'), 'user_ai_providers', ['user_uuid_bidx'], unique=False)
    op.add_column('user_settings', sa.Column('ai_feature_enabled', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('user_settings', sa.Column('ai_vision_provider', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user_settings', sa.Column('ai_chat_provider', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'ai_chat_provider')
    op.drop_column('user_settings', 'ai_vision_provider')
    op.drop_column('user_settings', 'ai_feature_enabled')
    op.drop_index(op.f('ix_user_ai_providers_user_uuid_bidx'), table_name='user_ai_providers')
    op.drop_table('user_ai_providers')
    op.drop_index(op.f('ix_cards_user_uuid_bidx'), table_name='cards')
    op.drop_table('cards')
    # ### end Alembic commands ###
