"""add notifications and community position first_bought_at

Revision ID: 97e6b1147cb5
Revises: 3c87d1280222
Create Date: 2026-08-16 16:11:35.699103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '97e6b1147cb5'
down_revision: Union[str, None] = '3c87d1280222'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Autogenerate also picked up pre-existing drift on refresh_tokens' index
    # and users.totp_last_used_step. Both are unrelated to this change and were
    # dropped: a migration should only carry what its message says.
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_uuid', sa.String(), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('actor_username', sa.String(length=50), nullable=True),
    sa.Column('asset_key', sa.String(length=30), nullable=True),
    sa.Column('message', sa.TEXT(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_uuid'], ['users.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_user_uuid'), 'notifications', ['user_uuid'], unique=False)
    op.add_column('community_positions', sa.Column('first_bought_at', sa.Date(), nullable=True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('community_positions', 'first_bought_at')
    op.drop_index(op.f('ix_notifications_user_uuid'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
