"""add_gross_deposits_and_withdrawals_to_account_history

Revision ID: a2088aa4e15f
Revises: acbbf762e7ac
Create Date: 2026-04-14 20:12:29.573953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a2088aa4e15f'
down_revision: Union[str, None] = 'acbbf762e7ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account_history', sa.Column('total_deposits_enc', sa.TEXT(), nullable=True))
    op.add_column('account_history', sa.Column('total_withdrawals_enc', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account_history', 'total_withdrawals_enc')
    op.drop_column('account_history', 'total_deposits_enc')
    # ### end Alembic commands ###
