"""add_market_assets_asset_type_column

Revision ID: b38e3b3aff98
Revises: q8r9s0t1u2v3
Create Date: 2026-03-28 10:36:07.700049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b38e3b3aff98'
down_revision: Union[str, None] = 'q8r9s0t1u2v3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    asset_type_enum = sa.Enum('STOCK', 'CRYPTO', 'COMMODITY', 'BOND', 'FIAT', name='assettype')
    asset_type_enum.create(op.get_bind(), checkfirst=True)
    op.execute(
        """
        UPDATE market_assets
        SET asset_type = NULL
        WHERE asset_type IS NOT NULL
          AND asset_type NOT IN ('STOCK', 'CRYPTO', 'COMMODITY', 'BOND', 'FIAT')
        """
    )
    op.alter_column('market_assets', 'asset_type',
               existing_type=sa.VARCHAR(),
               type_=asset_type_enum,
               postgresql_using='asset_type::assettype',
               existing_nullable=True)
    op.create_index(op.f('ix_market_assets_asset_type'), 'market_assets', ['asset_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    asset_type_enum = sa.Enum('STOCK', 'CRYPTO', 'COMMODITY', 'BOND', 'FIAT', name='assettype')
    op.drop_index(op.f('ix_market_assets_asset_type'), table_name='market_assets')
    op.alter_column('market_assets', 'asset_type',
               existing_type=asset_type_enum,
               type_=sa.VARCHAR(),
               postgresql_using='asset_type::varchar',
               existing_nullable=True)
    asset_type_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
