"""Initial migration

Revision ID: c669d294e844
Revises: 
Create Date: 2026-02-08 13:47:07.476522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c669d294e844'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_accounts',
    sa.Column('uuid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_uuid_bidx', sa.TEXT(), nullable=False),
    sa.Column('name_enc', sa.TEXT(), nullable=False),
    sa.Column('institution_name_enc', sa.TEXT(), nullable=True),
    sa.Column('identifier_enc', sa.TEXT(), nullable=True),
    sa.Column('balance_enc', sa.TEXT(), nullable=False),
    sa.Column('account_type_enc', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_bank_accounts_user_uuid_bidx'), 'bank_accounts', ['user_uuid_bidx'], unique=False)
    op.create_table('cashflows',
    sa.Column('uuid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_uuid_bidx', sa.TEXT(), nullable=False),
    sa.Column('name_enc', sa.TEXT(), nullable=False),
    sa.Column('flow_type_enc', sa.TEXT(), nullable=False),
    sa.Column('category_enc', sa.TEXT(), nullable=False),
    sa.Column('amount_enc', sa.TEXT(), nullable=False),
    sa.Column('frequency_enc', sa.TEXT(), nullable=False),
    sa.Column('transaction_date_enc', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_cashflows_user_uuid_bidx'), 'cashflows', ['user_uuid_bidx'], unique=False)
    op.create_table('crypto_accounts',
    sa.Column('uuid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_uuid_bidx', sa.TEXT(), nullable=False),
    sa.Column('name_enc', sa.TEXT(), nullable=False),
    sa.Column('platform_enc', sa.TEXT(), nullable=True),
    sa.Column('public_address_enc', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_crypto_accounts_user_uuid_bidx'), 'crypto_accounts', ['user_uuid_bidx'], unique=False)
    op.create_table('crypto_transactions',
    sa.Column('uuid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('account_id_bidx', sa.TEXT(), nullable=False),
    sa.Column('ticker_enc', sa.TEXT(), nullable=False),
    sa.Column('type_enc', sa.TEXT(), nullable=False),
    sa.Column('amount_enc', sa.TEXT(), nullable=False),
    sa.Column('price_per_unit_enc', sa.TEXT(), nullable=False),
    sa.Column('fees_enc', sa.TEXT(), nullable=False),
    sa.Column('fees_ticker_enc', sa.TEXT(), nullable=True),
    sa.Column('executed_at_enc', sa.TEXT(), nullable=False),
    sa.Column('tx_hash_enc', sa.TEXT(), nullable=True),
    sa.Column('notes_enc', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_crypto_transactions_account_id_bidx'), 'crypto_transactions', ['account_id_bidx'], unique=False)
    op.create_table('market_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('current_price', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_prices_symbol'), 'market_prices', ['symbol'], unique=True)
    op.create_table('notes',
    sa.Column('uuid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_uuid_bidx', sa.TEXT(), nullable=False),
    sa.Column('name_enc', sa.TEXT(), nullable=False),
    sa.Column('description_enc', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_notes_user_uuid_bidx'), 'notes', ['user_uuid_bidx'], unique=False)
    op.create_table('stock_accounts',
    sa.Column('uuid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_uuid_bidx', sa.TEXT(), nullable=False),
    sa.Column('name_enc', sa.TEXT(), nullable=False),
    sa.Column('institution_name_enc', sa.TEXT(), nullable=True),
    sa.Column('identifier_enc', sa.TEXT(), nullable=True),
    sa.Column('account_type_enc', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_stock_accounts_user_uuid_bidx'), 'stock_accounts', ['user_uuid_bidx'], unique=False)
    op.create_table('stock_transactions',
    sa.Column('uuid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('account_id_bidx', sa.TEXT(), nullable=False),
    sa.Column('ticker_enc', sa.TEXT(), nullable=False),
    sa.Column('exchange_enc', sa.TEXT(), nullable=True),
    sa.Column('type_enc', sa.TEXT(), nullable=False),
    sa.Column('amount_enc', sa.TEXT(), nullable=False),
    sa.Column('price_per_unit_enc', sa.TEXT(), nullable=False),
    sa.Column('fees_enc', sa.TEXT(), nullable=False),
    sa.Column('executed_at_enc', sa.TEXT(), nullable=False),
    sa.Column('notes_enc', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_stock_transactions_account_id_bidx'), 'stock_transactions', ['account_id_bidx'], unique=False)
    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_uuid_bidx', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('objectives_enc', sa.TEXT(), nullable=True),
    sa.Column('theme', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dashboard_layout_enc', sa.TEXT(), nullable=True),
    sa.Column('flat_tax_rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('tax_pea_rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('yield_expectation', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('inflation_rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_settings_user_uuid_bidx'), 'user_settings', ['user_uuid_bidx'], unique=False)
    op.create_table('users',
    sa.Column('uuid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('auth_salt', sa.TEXT(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_uuid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_uuid'], ['users.uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_token'), 'refresh_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_uuid'), 'refresh_tokens', ['user_uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refresh_tokens_user_uuid'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_user_settings_user_uuid_bidx'), table_name='user_settings')
    op.drop_table('user_settings')
    op.drop_index(op.f('ix_stock_transactions_account_id_bidx'), table_name='stock_transactions')
    op.drop_table('stock_transactions')
    op.drop_index(op.f('ix_stock_accounts_user_uuid_bidx'), table_name='stock_accounts')
    op.drop_table('stock_accounts')
    op.drop_index(op.f('ix_notes_user_uuid_bidx'), table_name='notes')
    op.drop_table('notes')
    op.drop_index(op.f('ix_market_prices_symbol'), table_name='market_prices')
    op.drop_table('market_prices')
    op.drop_index(op.f('ix_crypto_transactions_account_id_bidx'), table_name='crypto_transactions')
    op.drop_table('crypto_transactions')
    op.drop_index(op.f('ix_crypto_accounts_user_uuid_bidx'), table_name='crypto_accounts')
    op.drop_table('crypto_accounts')
    op.drop_index(op.f('ix_cashflows_user_uuid_bidx'), table_name='cashflows')
    op.drop_table('cashflows')
    op.drop_index(op.f('ix_bank_accounts_user_uuid_bidx'), table_name='bank_accounts')
    op.drop_table('bank_accounts')
    # ### end Alembic commands ###